[package]
name = "nav-types"
version = "0.3.0"
authors = ["Jørgen Nordmoen <nordmoen90@gmail.com>"]
description = "Easily work with global positions and vectors"
edition = "2018"

homepage = "https://github.com/nordmoen/nav-types"
repository = "https://github.com/nordmoen/nav-types.git"
documentation = "https://docs.rs/nav-types/"

keywords = ["nav", "navigation", "ecef", "latitude", "wgs84"]
license = "MIT"

[dependencies]
clippy = { version = "0.0.112", optional = true }
nalgebra = "0.10"
num-traits = "0.1.36"

[dev-dependencies]
assert = "0.7"
quickcheck = "0.4"

[features]
default = []
dev = ["clippy"]
